using System;
using System.Reflection;
using System.Resources;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.17379
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: CLSCompliantAttribute(false)]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyTitleAttribute("NSoft.NAccess.Tests for Microsoft .NET Framework 4.0")]
[assembly: AssemblyDescriptionAttribute("NSoft.NAccess.Tests Library")]
[assembly: AssemblyCompanyAttribute("http://www.nsoft.com")]
[assembly: AssemblyProductAttribute("NSoft.NAccess.Tests")]
[assembly: AssemblyCopyrightAttribute("NSoft. All rights reserved.")]
[assembly: AssemblyVersionAttribute("4.0.0.0")]
[assembly: AssemblyInformationalVersionAttribute("4.0.0.0")]
[assembly: AssemblyFileVersionAttribute("4.0.0.0")]
[assembly: SatelliteContractVersionAttribute("4.0.0.0")]
[assembly: AssemblyDelaySignAttribute(false)]
[assembly: NeutralResourcesLanguageAttribute("ko-KR")]
[assembly: ObfuscationAttribute(Feature="string encryption", Exclude=false)]
[assembly: ObfuscationAttribute(Feature="rename symbol names with printable characters", Exclude=false)]

